name: dotnet-sdk
version: 3.1.402
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

grade: stable
confinement: classic
base: core20

apps:
  dotnet:
    command: dotnet
    environment:
      DOTNET_ROOT: $SNAP # Not required?
      #LD_LIBRARY_PATH: $SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH # Required to find libicu in classic.

parts:
  dotnet-sdk:
      plugin: dump
      source:
        - on amd64: https://download.visualstudio.microsoft.com/download/pr/f01e3d97-c1c3-4635-bc77-0c893be36820/6ec6acabc22468c6cc68b61625b14a7d/dotnet-sdk-3.1.402-linux-x64.tar.gz
        - on arm64: https://download.visualstudio.microsoft.com/download/pr/186257d9-bca2-4dda-be74-006205965ec9/b2b63d45482701473d9731abc41ecc2a/dotnet-sdk-3.1.402-linux-arm64.tar.gz
        - on armhf: https://download.visualstudio.microsoft.com/download/pr/8f0dffe3-18f0-4d32-beb0-dbcb9a0d91a1/abe9a34e3f8916478f0bd80402b01b38/dotnet-sdk-3.1.402-linux-arm.tar.gz

      #build-attributes: [no-patchelf]

      stage-packages:
        - libicu66
        - libssl1.1
        - libcurl4
        - libgssapi-krb5-2
        - libstdc++6
        - zlib1g
        - libgcc1
        - libtinfo5
        - liblttng-ust0
        - liburcu6

      override-prime: |
        set -x
        snapcraftctl prime

        patchelf="/snap/snapcraft/current/bin/patchelf"
        base="/snap/core20/current"

        # Snapcraft sets rpath and rewrites the interpreter to point to the snap base.
        # Revert this change for the apphost template binaries.
        for f in $(find "$SNAPCRAFT_PRIME" -name apphost); do
          # Use original rpath (required?).
          rpath='$ORIGIN/netcoredeps'

          # Sanity check to make sure we are pointing to a valid interpreter.
          interp="$("${patchelf}" --print-interpreter "${f}" | sed "s|$base||")"
          if [ ! -f "${interp}" ]; then
            echo "${interp} not found"
            exit 1
          fi

          #"${patchelf}" --force-rpath --set-rpath "${rpath}" "${f}"
          #"${patchelf}" --set-interpreter "${interp}" "${f}"
        done

  runtime-wrapper:
      plugin: dump
      source: .

